### PR TITLE
Update to latest cf-uaac

### PR DESCRIPTION
**Pull request by william-tran**
Adds zone admin support in uaac

### CODE REVIEW

**Comment by scottfrederick** [comment]
Also fixes this issue in uaac: https://github.com/cloudfoundry/cf-uaac/issues/19

**Comment by scottfrederick** [comment]
@drnic The issue mentioned above with uaac bit us when we upgraded to latest traveling-cf-admin. It is likely to bite others also. Can we get this PR merged?

**Comment by drnic** [comment]
Merged and recreated latest release via pipeline. Thanks!

On Tue, Apr 5, 2016 at 10:20 AM -0700, "Scott Frederick" notifications@github.com wrote:

@drnic The issue mentioned above with uaac bit us when we upgraded to latest traveling-cf-admin. It is likely to bite others also. Can we get this PR merged?

**Comment by scottfrederick** [comment]
Thanks @drnic

**Pull request merged**
